### ISSUE TITLE
ESLintの導入。

### ISSUE THREAD

**Issue by kobayashi-m42** [kobayashi-m42/javascript-lessons#11]

**Comment by keitakn** [comment]
以前は Airbnbのスタイルが良いみたいな話をしてたけど、今やる場合は [Prettier](https://github.com/prettier/prettier) というツールとESLintを組み合わせるのがベストだよ！

（参考）ESLint(あるいはTSLint)とPrettierを併用する
http://tech-1natsu.hatenablog.com/entry/2018/01/07/154941

有名なオープンソースでも続々採用されてて、ESLintだけでは出来なかった、自動修正の範囲も広がってるしいい感じ👍
